### ISSUE TITLE
Dail-pad Isssue - ayoo App

### ISSUE THREAD

**Issue by sureshkumarmuthukrishnan** [telecmi/TeleCMI-Support#123]
While calling from ayoo app and opening the dialpad during the call and ending the call without closing the dialpad. But at the next time of calling from the app the dialpad is still open.

**Comment by murugancmi** [comment]
Hope Dialpad Mean DTMF DIalplan in outbound call modal ,Let me check and fix it

**Comment by murugancmi** [comment]
issue fixed please check new AYOO apk in repo
