### ISSUE TITLE
voting ivr tab 

### ISSUE THREAD

**Issue by masthantelecmi** [telecmi/TeleCMI-Support#13]
i have completed the voting ivr and if suppose i want to change the welcome ivr or invalid key music ivr there is no edit option available to edit my voting ivr. there is only delete  option available.

**Comment by murugancmi** [comment]
We can't able to give edit option to Vote IVR,Because once people vote one option you cant change that option right so that why we dont have edit option for VOTE IVR,And its technical problem too :)

**Comment by masthantelecmi** [comment]
Yes that is fine. I mean, suppose i have to edit before launching my voting or else i have to delete again and i have create a new one again.

**Comment by murugancmi** [comment]
yes if you need to change just delete and create new one,Once you created vote IVR you can't able to edit its limitation right now

**Comment by murugancmi** [comment]
i am closing this right now,If we need we may open in feature
