### ISSUE TITLE
Ayyo App CDR issue

### ISSUE THREAD

**Issue by Ravikumarselvam** [telecmi/TeleCMI-Support#138]
When i call using ayoo app to mobile number which is added as pstn number in our app, i could not able to see the cdr details for the specific numbers.

**Comment by murugancmi** [comment]
When you try to call internet virtual number from AYOO,ChubCTM and kalamfone you cant able to see call log in you app, the log should present in Internet Virtual Number ,So it's not issue AYOO app show only pstn log
