### ISSUE TITLE
music tab

### ISSUE THREAD

**Issue by masthantelecmi** [telecmi/TeleCMI-Support#14]
In music upload section there are two options available for uploading the audio 1. click here to upload manually and 2. drag and drop an audio file. But the first option is not working most of the times. Only the drag and drop option is working correctly.

**Comment by murugancmi** [comment]
Its purely based on your system resurce when you click select file its access your file system ,If your system have low configuration its take long time some time it fail,But of your system performance is good it should work ,Its already working mine and our desktops :)

**Comment by masthantelecmi** [comment]
Even though i have good configuration it is not working. but if i choose file upload option in some other website it is working fine. Only it becomes slow in music tab upload section. ?

**Comment by murugancmi** [comment]
Its work @Ravikumarselvam and @prasathsekar
