### ISSUE TITLE
kalamfone call receiving

### ISSUE THREAD

**Issue by masthantelecmi** [telecmi/TeleCMI-Support#21]
When i try to receive the call in kalamfone it is not working. I have logged in as a agent in kalamfone.  It is not working as i have tried all the possible ways.

**Comment by murugancmi** [comment]
look like me freeswitch behind nginx so when freeswitch send invite to nginx ip not actual ip of client so we need to change private ip of freeswitch into public ip of freeswitch

**Comment by murugancmi** [comment]
So better we create new domain for kalamfone ,so please use this domain kalam.telecmi.com
