### ISSUE TITLE
Agent Analysis agent name  not showing properly

### ISSUE THREAD

**Issue by masthantelecmi** [telecmi/TeleCMI-Support#25]
In the analysis details tab, the 'from' and 'agent name' is not displaying with proper data it is keep on changing the data and showing various names and numbers at each call.

![analysisdetails2](https://cloud.githubusercontent.com/assets/25261678/22236296/c76b66a8-e22a-11e6-82c7-3ab3462c9532.png)

**Comment by RajarajanTelecmi** [comment]
issue fixed
