### ISSUE TITLE
analysis tab

### ISSUE THREAD

**Issue by masthantelecmi** [telecmi/TeleCMI-Support#26]
In the analysis tab, the right side chart keep on changing the agent name in the left and right and vice versa while reloading the dashboard.

![analysis1](https://cloud.githubusercontent.com/assets/25261678/22236741/98431d28-e22d-11e6-8426-a62cb74f5967.png)
![analysis2](https://cloud.githubusercontent.com/assets/25261678/22236742/9846ee08-e22d-11e6-9672-683cfcb14275.png)

**Comment by murugancmi** [comment]
look like its not issue ,its Dynamic one it always change

**Comment by masthantelecmi** [comment]
am opening this issue again, because now it is showing me only the answerd calls for only one agent. the missed calls and other calls for another agent is not displaying. attaching screenshot for the latest one.

![analysis details3](https://cloud.githubusercontent.com/assets/25261678/22238565/31670a82-e238-11e6-9c1c-4e1f488b49c6.png)

**Comment by murugancmi** [comment]
It should work because its work @prasathsekar @RajarajanTelecmi @Ravikumarselvam
