### ISSUE TITLE
call details tab

### ISSUE THREAD

**Issue by masthantelecmi** [telecmi/TeleCMI-Support#27]
in call details tab, the total call duration is '1 min 24 sec' and it costs '0.60 p' and at the top it shows for talking with agent cost as '1 min 14 sec' and the cost is '1.30 p' . i don't think so it is deducting the right cost .
 check the top two calls in the call details screenshot attached.

![call details](https://cloud.githubusercontent.com/assets/25261678/22238331/d530e36a-e236-11e6-8689-d96ed002a3bf.png)

**Comment by murugancmi** [comment]
look like me its work fine you may consider 8 to 9 sec we need take time to complete process in our server

**Comment by masthantelecmi** [comment]
this is the recent scenario, this is totally different.

![call details2](https://cloud.githubusercontent.com/assets/25261678/22251023/4adbf540-e26f-11e6-9d6b-34bc57ec457b.png)

**Comment by murugancmi** [comment]
Yup i understand but we cant avoid that because one side always internet other side PSTN,Our serverwill  bill based on when its receive Bye message from provider ,if you face any issue based on money fell free open this
