### ISSUE TITLE
Recording tab issue 1

### ISSUE THREAD

**Issue by masthantelecmi** [telecmi/TeleCMI-Support#28]
I have just downloaded and played the recorded voice calls.The first few seconds have some irritated noise and in the second part i can heard the voice....

**Comment by murugancmi** [comment]
Recording always start with echo so i dont think so its issue

**Comment by masthantelecmi** [comment]
No...It is not an echo... It is an unwanted noise.

**Comment by murugancmi** [comment]
It purely based on your packet lass it may happen ,we cant avoid that because its through UDP .Just i am closing now we may open in feature
