### ISSUE TITLE
Recording Length more then answered mins

### ISSUE THREAD

**Issue by masthantelecmi** [telecmi/TeleCMI-Support#29]
i have talked in a voice call for 1min 14sec. But, when i downloaded the recorded voice of the call it shows me 5 mins. when i started to play the recorded voice, the first 1 min 14 sec is same as i have talked in the call. But, the remaining portion of the recorded voice call is completely blank.

**Comment by murugancmi** [comment]
OK let me check

**Comment by murugancmi** [comment]
We may need to ask this in freeswitch forum

**Comment by murugancmi** [comment]
it purely based on our up link

**Comment by murugancmi** [comment]
enhancement
