### ISSUE TITLE
Multiple OTP recived  @ Indian.telecmi

### ISSUE THREAD

**Issue by RajarajanTelecmi** [telecmi/TeleCMI-Support#33]
In "Indian Tc" i was created new account, initially they request mobile number for "OTP" after revising OTP i entered OTP after that i am clicking the "ENTER" button it will not go to the next page. Unfortunately it generate a another new "OTP". 

Expected result: "When i am giving "Enter" it will validation the OTP if its correct OTP means it will go to next page.

Actual result:    "When i am giving "Enter" it will generate new "OTP"

**Comment by murugancmi** [comment]
Nice work,Issue fixed
