### ISSUE TITLE
CRM for BPO and small business 

### ISSUE THREAD

**Issue by murugancmi** [telecmi/TeleCMI-Support#49]
We need to develop callcenter  based CRM for startup,with following feature 

1.Store contact details
2.Receive call from Website(browser)
3.Receive call from International mobile number
4.Make outbound call to all country
5.Desktop Application Development

**Comment by murugancmi** [comment]
Work in progress with following feature

1.Contact Details
2. Lead 
3.Sales
4.Call History
5.Make outbount call
6.Receive call from browser
7.Receive call from InetNo
8.Receive call from International number(Tollfree and Virtual Number)
9.Make internation call
10.Agent Call details 
11.Admin watching

**Comment by telecmi** [comment]
We may be open source this Project, It may be the first opensource CRM include Telephony feature @murugancmi

**Comment by murugancmi** [comment]
We cant able to opensource now maybe in feature and we added WebRTC one-to-one video chat using https://github.com/nari so

one more feature 
12.Video and Audio chat

**Comment by murugancmi** [comment]
CRM ready to use with above 12 feature
