### ISSUE TITLE
Can't create an app in click2call in dashboard

### ISSUE THREAD

**Issue by masthantelecmi** [telecmi/TeleCMI-Support#6]
It tells that "this service  is not available in your country"

**Comment by murugancmi** [comment]
Now we cover click2call feature in contactHUB so we don't need click2call

**Comment by masthantelecmi** [comment]
then we can remove the Click2call from there....

**Comment by murugancmi** [comment]
May be in feature we can enable click2call based on customer

**Comment by murugancmi** [comment]
so now i close this issue,if you need open in feature
