### ISSUE TITLE
Student Info Issue

### ISSUE THREAD

**Issue by sureshkumarmuthukrishnan** [telecmi/TeleCMI-Support#62]
I have uploaded the student info csv file, by mentioning "Register Number, Attendance, Marks, Class, Section, Name, Email ID" at the top of the csv file. After uploading the file the " Register Number, Attendance, Marks, Class, Section, Name, Email ID " appears in the page and it could not be deleted.

**Comment by murugancmi** [comment]
Now student info format should be same as from dashboard , and now you can delete student
