### ISSUE TITLE
Agent Update

### ISSUE THREAD

**Issue by sureshkumarmuthukrishnan** [telecmi/TeleCMI-Support#68]
I already created Agent in my account, I try to edit created agent and save it work fine, But when i try to create new agent in name field it shows created agent name look like me its not refreshed

**Comment by murugancmi** [comment]
issue fixed @sureshkumarmuthukrishnan  now you can check in production admin tool :100:

**Comment by sureshkumarmuthukrishnan** [comment]
It's fine ,everything is ok now.
