### ISSUE TITLE
ContactHub app creation issue in plan section

### ISSUE THREAD

**Issue by masthantelecmi** [telecmi/TeleCMI-Support#7]
Only one plan available in all three categories

**Comment by telecmi** [comment]
If you need we will add more plan ,For testing i hope one plan enough

**Comment by masthantelecmi** [comment]
okay that is fine. i can see only three categories. but there should be four ?(indian, international, call centre, inetno) ...

**Comment by murugancmi** [comment]
Yes callcenter plan should be but look like me enhancement

**Comment by murugancmi** [comment]
Enhancement added
