### ISSUE TITLE
ContactHUB payment failure scenario

### ISSUE THREAD

**Issue by masthantelecmi** [telecmi/TeleCMI-Support#8]
When the ContactHUB payment gets failed the whole UI of page gets collapsed and all went to bad alignment.

**Comment by RajarajanTelecmi** [comment]
Masthan ji, Which browser you are using

**Comment by prabhutelecmi** [comment]
Mozilla firefox

**Comment by masthantelecmi** [comment]
Mozilla firefox

**Comment by murugancmi** [comment]
Please elaborate in details if you attach image its help to fix

**Comment by masthantelecmi** [comment]
![paymentfailure](https://cloud.githubusercontent.com/assets/25261678/22173321/6785bdca-dfe5-11e6-9892-265c10ec7837.png)

**Comment by murugancmi** [comment]
issue fixed
