### ISSUE TITLE
Test ContactHUB Telephony CRM

### ISSUE THREAD

**Issue by telecmi** [telecmi/TeleCMI-Support#83]
Test ContactHUB Telephony CRM

**Comment by sureshkumarmuthukrishnan** [comment]
Lead-Generates and Sales field  notification is not showing in Telephony CRM

**Comment by sureshkumarmuthukrishnan** [comment]
It's working good.

**Comment by sureshkumarmuthukrishnan** [comment]
Making call in CRM ,Ivr option enter the value buttons is not working properly in CRM.

**Comment by sureshkumarmuthukrishnan** [comment]
Call Details : Only last five call dialed numbers showing. scrolling buttons option not in call details

**Comment by sureshkumarmuthukrishnan** [comment]
Out-bounding calls unable to  hear the ringing voice  for PSTN

**Comment by murugancmi** [comment]
issue fixed please check new version of exe or deb
