### ISSUE TITLE
Check Indian Plan And recharge 

### ISSUE THREAD

**Issue by telecmi** [telecmi/TeleCMI-Support#87]
Check indian plan and recharge and rental , The plan id should match following prefix https://github.com/telecmi/country-Data/blob/master/plan.md  and for payment please use following test account from instamojo 

Number: 4242 4242 4242 4242

Date: Any valid future date

CVV: 111

Name: abc

3D-secure password: 1221

**Comment by Ravikumarselvam** [comment]
I check that issues in production,It's good ,No issue in production

**Comment by sureshkumarmuthukrishnan** [comment]
I check with Indian Plan in  Rental, Recharge, No issues there it's working now
