### ISSUE TITLE
Voting dashbord 

### ISSUE THREAD

**Issue by Ravikumarselvam** [telecmi/TeleCMI-Support#90]
I have create one app and create vote ivr and put voting its working good, but when i create another new app in same account the voting status is displaying that app also.(refer account: username=ravikumar@telecmi.com, pass=XXXXX)

**Comment by murugancmi** [comment]
Issue fixed please check in production

**Comment by Ravikumarselvam** [comment]
ok

**Comment by Ravikumarselvam** [comment]
Now i checked voting result in dashboard, there  is nothing to display in my old app and new app.
